# Generated by Django 2.0 on 2018-01-31 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('cat_descr', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField()),
                ('chapter_title', models.CharField(max_length=64)),
                ('chapter_text', models.TextField()),
                ('chapter_flag_hidden', models.BooleanField(default=False)),
                ('chapter_release', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_firstname', models.CharField(blank=True, max_length=32)),
                ('char_surname', models.CharField(blank=True, max_length=32)),
                ('char_name', models.CharField(default='blank', editable=False, max_length=100)),
                ('char_descr', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fandom_name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('fandom_descr', models.TextField(blank=True, max_length=1200)),
                ('fandom_short', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=256)),
                ('story_description', models.TextField()),
                ('story_initial_release', models.DateTimeField(auto_now_add=True)),
                ('story_last_modified', models.DateTimeField(auto_now_add=True)),
                ('auto_uid', models.CharField(blank=True, db_index=True, editable=False, max_length=8, unique=True)),
                ('story_is_save', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fandom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff2ksite.Fandom')),
                ('story_cat', models.ManyToManyField(to='ff2ksite.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=32)),
                ('tag_descr', models.TextField(blank=True, max_length=1200)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='story_tags',
            field=models.ManyToManyField(to='ff2ksite.Tags'),
        ),
        migrations.AddField(
            model_name='character',
            name='fandom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff2ksite.Fandom'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff2ksite.Story'),
        ),
    ]
